### ISSUE TITLE
Game assets

### ISSUE THREAD

**Issue by sho-87** [Nkmol/RoC-talent-tree#7]
I'm working on a similar project to this for the most recent version of the game. I'm wondering where you got the game assets/talent icon images from? Is there a way to unpack them from the apk file?

**Comment by Nkmol** [comment]
@sho-87 Hi, thanks for creating a ticket for this :) And great to see you are also working on something similar. I have to admit that I have been inactive the lost months, as I was trying to create this for the updated game.

I occasionally upload the *compressed* assets to Google Drive, which is officially managed by Lilith Games: https://drive.google.com/drive/folders/1hcQPOzcqj3qiWtpOgH38oujVjTnjTY9T

Let me know if this solves the issue :)

**Comment by sho-87** [comment]
oh wow, had no idea that existed. It is perfect, thanks so much!
